apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen-app-0523 
  janus-idp.io/tekton: codegen-app-0523
  backstage.io/kubernetes-id: codegen-app-0523
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: codegen-app-0523
resources: 
- application-dev.yaml